# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginRuntimeStub:
    """Wire contract between eumeaus-engine (via eumeaus-plugin-host) and plugin
    subprocesses. Single source of truth both sides compile against.

    Compiled by build.rs (tonic-build, via a vendored protoc so no system
    install is required) into $OUT_DIR, then pulled in by
    `tonic::include_proto!("eumeaus.plugin.v1")` in src/lib.rs.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/eumeaus.plugin.v1.PluginRuntime/Describe',
                request_serializer=plugin__pb2.DescribeRequest.SerializeToString,
                response_deserializer=plugin__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_stream(
                '/eumeaus.plugin.v1.PluginRuntime/Check',
                request_serializer=plugin__pb2.CheckRequest.SerializeToString,
                response_deserializer=plugin__pb2.CheckResult.FromString,
                _registered_method=True)


class PluginRuntimeServicer:
    """Wire contract between eumeaus-engine (via eumeaus-plugin-host) and plugin
    subprocesses. Single source of truth both sides compile against.

    Compiled by build.rs (tonic-build, via a vendored protoc so no system
    install is required) into $OUT_DIR, then pulled in by
    `tonic::include_proto!("eumeaus.plugin.v1")` in src/lib.rs.

    """

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=plugin__pb2.DescribeRequest.FromString,
                    response_serializer=plugin__pb2.DescribeResponse.SerializeToString,
            ),
            'Check': grpc.unary_stream_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=plugin__pb2.CheckRequest.FromString,
                    response_serializer=plugin__pb2.CheckResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eumeaus.plugin.v1.PluginRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eumeaus.plugin.v1.PluginRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginRuntime:
    """Wire contract between eumeaus-engine (via eumeaus-plugin-host) and plugin
    subprocesses. Single source of truth both sides compile against.

    Compiled by build.rs (tonic-build, via a vendored protoc so no system
    install is required) into $OUT_DIR, then pulled in by
    `tonic::include_proto!("eumeaus.plugin.v1")` in src/lib.rs.

    """

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eumeaus.plugin.v1.PluginRuntime/Describe',
            plugin__pb2.DescribeRequest.SerializeToString,
            plugin__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eumeaus.plugin.v1.PluginRuntime/Check',
            plugin__pb2.CheckRequest.SerializeToString,
            plugin__pb2.CheckResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
